# -*- coding: utf-8 -*-
"""1&3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10CmjI6R4w6xr9eUN5LFiPHPGJth4aTuk

### **CMAPSS**

## **FD001 PHASE 1:-**
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import os

from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans
from sklearn.decomposition import PCA
from sklearn.manifold import TSNE

import tensorflow as tf
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Input, Dense

import kagglehub

path = kagglehub.dataset_download("behrad3d/nasa-cmaps")

print("Path to dataset files:", path)

import os

# This should show you the folder names inside the downloaded dataset
print(os.listdir(path))

import pandas as pd

# Define column names
column_names = ['unit_number', 'time_in_cycles'] + \
               [f'operational_setting_{i}' for i in range(1, 4)] + \
               [f'sensor_measurement_{i}' for i in range(1, 22)]

# Load FD001
df = pd.read_csv(f"{path}/CMaps/train_FD001.txt", sep=" ", header=None)
df.dropna(axis=1, how='all', inplace=True)
df.columns = column_names
df['source'] = 'FD001'

# Display shape and first few rows
print("Shape of the FD001 dataset:", df.shape)
df.head()

"""The first step is to cluster the data into 5 stages:
- normal(0)
- degraded(1)
- highly degraded(2)
- critical(3)
- failure(4)
"""

# Select only sensor measurements
sensor_cols = [col for col in df.columns if 'sensor' in col]
X = df[sensor_cols]

# Scale the data
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

import tensorflow as tf
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Input, Dense

input_dim = X_scaled.shape[1]
encoding_dim = 8

# Define Autoencoder
input_layer = Input(shape=(input_dim,))
encoded = Dense(16, activation='relu')(input_layer)
encoded = Dense(encoding_dim, activation='relu')(encoded)

decoded = Dense(16, activation='relu')(encoded)
decoded = Dense(input_dim, activation='linear')(decoded)

autoencoder = Model(inputs=input_layer, outputs=decoded)
encoder = Model(inputs=input_layer, outputs=encoded)

autoencoder.compile(optimizer='adam', loss='mse')
autoencoder.fit(X_scaled, X_scaled, epochs=50, batch_size=256, shuffle=True, verbose=1)

# Encode the input data
X_encoded = encoder.predict(X_scaled)

# KMeans clustering
from sklearn.cluster import KMeans

kmeans = KMeans(n_clusters=5, random_state=42)
df['cluster'] = kmeans.fit_predict(X_encoded)

# Sample for plotting
sample_df = df.sample(5000, random_state=42)

# Plot some key sensors
sensors_to_plot = ['sensor_measurement_2', 'sensor_measurement_3', 'sensor_measurement_4']

for sensor in sensors_to_plot:
    plt.figure(figsize=(12,6))
    sns.lineplot(x='time_in_cycles', y=sensor, hue='cluster', data=sample_df, palette='tab10')
    plt.title(f"{sensor} vs Time for Different Clusters")
    plt.xlabel('Time in Cycles')
    plt.ylabel(sensor)
    plt.legend(title='Cluster')
    plt.grid(True)
    plt.show()

# Add a 'stage' column based on the 'cluster' column
df['stage'] = df['cluster'].map({0: 'normal', 1: 'degraded', 2: 'highly degraded', 3: 'critical', 4: 'failure'})

from sklearn.manifold import TSNE
import matplotlib.pyplot as plt
import numpy as np # Make sure numpy is imported

# Run t-SNE on encoded features
tsne = TSNE(n_components=2, perplexity=30, n_iter=300, random_state=42)
X_tsne = tsne.fit_transform(X_encoded)

# Add t-SNE results to DataFrame
df['tsne-1'] = X_tsne[:, 0]
df['tsne-2'] = X_tsne[:, 1]

# Define unique stages and colors
stages = df['stage'].unique()
colors = plt.cm.viridis(np.linspace(0, 1, len(stages)))

# Plot manually using matplotlib
plt.figure(figsize=(10, 6))
for i, stage in enumerate(sorted(stages)):
    subset = df[df['stage'] == stage]
    plt.scatter(subset['tsne-1'], subset['tsne-2'], label=f'Stage {stage}', color=colors[i], alpha=0.7)

plt.title("t-SNE Visualization of Engine Health Stages")
plt.xlabel("t-SNE Component 1")
plt.ylabel("t-SNE Component 2")
plt.legend(title='Stage')
plt.grid(True)
plt.show()

"""## **Phase 2:-**"""

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import classification_report, confusion_matrix

# Define column names
column_names = ['unit_number', 'time_in_cycles'] + \
               [f'op_setting_{i}' for i in range(1, 4)] + \
               [f'sensor_measurement_{i}' for i in range(1, 22)]

# Load and label source
def load_file(path, fname, source):
    df = pd.read_csv(f"{path}/CMaps/{fname}", sep=" ", header=None)
    df.dropna(axis=1, how='all', inplace=True)
    df.columns = column_names
    df['source'] = source
    return df

# Replace 'path' with your actual dataset path
train_df = pd.concat([
    load_file(path, "train_FD001.txt", "FD001")
], ignore_index=True)

test_df = pd.concat([
    load_file(path, "test_FD001.txt", "FD001")
], ignore_index=True)

from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler

# Feature columns
sensor_cols = [col for col in train_df.columns if 'sensor_measurement' in col]

# Normalize sensor data
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(train_df[sensor_cols])

# Apply KMeans clustering (same as Phase 1)
kmeans = KMeans(n_clusters=5, random_state=42)
train_df['cluster'] = kmeans.fit_predict(X_train_scaled)

# Scale test data using training scaler
X_test_scaled = scaler.transform(test_df[sensor_cols])

# Labels (y_train from cluster labels)
X_train = train_df[sensor_cols]
y_train = train_df['cluster']

X_test = test_df[sensor_cols]  # Note: test labels are unknown in CMAPSS, so just predict

clf = RandomForestClassifier(n_estimators=100, random_state=42, class_weight='balanced')
clf.fit(X_train_scaled, y_train)

y_pred_test = clf.predict(X_test_scaled)

# Assign predictions to test dataframe
test_df['predicted_stage'] = y_pred_test

stage_map = {
    0: 'Stage 0: Normal',
    1: 'Stage 1: Slightly Degraded',
    2: 'Stage 2: Moderately Degraded',
    3: 'Stage 3: Critical',
    4: 'Stage 4: Failure'
}
test_df['predicted_stage_name'] = test_df['predicted_stage'].map(stage_map)

print("Stage distribution in test predictions:")
print(test_df['predicted_stage_name'].value_counts())

# Optional visualization
plt.figure(figsize=(10,6))
sns.countplot(data=test_df, x='predicted_stage_name', order=stage_map.values())
plt.title("Predicted Stages on Official Test Data")
plt.xlabel("Degradation Stage")
plt.ylabel("Count")
plt.grid(True)
plt.xticks(rotation=30)
plt.show()

# Reuse existing train_df with cluster labels
from sklearn.model_selection import train_test_split # Import train_test_split

X = train_df[sensor_cols]
y = train_df['cluster']

X_train_cv, X_val_cv, y_train_cv, y_val_cv = train_test_split(
    X, y, test_size=0.2, stratify=y, random_state=42
)

X_train_cv_scaled = scaler.fit_transform(X_train_cv)
X_val_cv_scaled = scaler.transform(X_val_cv)

clf_cv = RandomForestClassifier(n_estimators=100, random_state=42, class_weight='balanced')
clf_cv.fit(X_train_cv_scaled, y_train_cv)
y_pred_cv = clf_cv.predict(X_val_cv_scaled)

stage_names = ['Stage 0: Normal', 'Stage 1: Slightly Degraded', 'Stage 2: Moderately Degraded',
               'Stage 3: Critical', 'Stage 4: Failure']

print("Classification Report (Train Split Evaluation):\n")
print(classification_report(y_val_cv, y_pred_cv, target_names=stage_names))

cm = confusion_matrix(y_val_cv, y_pred_cv)
plt.figure(figsize=(8,6))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
            xticklabels=stage_names, yticklabels=stage_names)
plt.title("Confusion Matrix (Train-Only Cross-Validation)")
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.xticks(rotation=45)
plt.yticks(rotation=0)
plt.tight_layout()
plt.show()

# Use trained classifier from CV: clf_cv and sensor_cols
importances = clf_cv.feature_importances_
indices = np.argsort(importances)[::-1]

top_n = 10  # Number of top features to show
top_features = [sensor_cols[i] for i in indices[:top_n]]
top_scores = importances[indices[:top_n]]

plt.figure(figsize=(10, 6))
sns.barplot(x=top_scores, y=top_features)
plt.title("Top 10 Sensor Features by Importance (Random Forest)")
plt.xlabel("Importance Score")
plt.ylabel("Sensor Feature")
plt.grid(True)
plt.tight_layout()
plt.show()

import xgboost as xgb

# Use same stratified split as before
X = train_df[sensor_cols]
y = train_df['cluster']

X_train_xgb, X_val_xgb, y_train_xgb, y_val_xgb = train_test_split(
    X, y, test_size=0.2, stratify=y, random_state=42
)

# Scale inputs
scaler_xgb = StandardScaler()
X_train_xgb_scaled = scaler_xgb.fit_transform(X_train_xgb)
X_val_xgb_scaled = scaler_xgb.transform(X_val_xgb)

# Define and train model
xgb_model = xgb.XGBClassifier(
    objective='multi:softmax',
    num_class=5,
    eval_metric='mlogloss',
    use_label_encoder=False,
    n_estimators=100,
    max_depth=6,
    learning_rate=0.1,
    random_state=42
)

xgb_model.fit(X_train_xgb_scaled, y_train_xgb)

# Sort the training data by unit and cycle
train_df = train_df.sort_values(by=['unit_number', 'time_in_cycles'])

# Set window size for rolling calculations
window_size = 5

# Sensor columns
sensor_cols = [col for col in train_df.columns if 'sensor_measurement' in col]

# Create new rolling statistic columns
for sensor in sensor_cols:
    # Rolling mean
    train_df[f'{sensor}_roll_mean'] = train_df.groupby('unit_number')[sensor] \
        .transform(lambda x: x.rolling(window=window_size, min_periods=1).mean())

    # Rolling std dev
    train_df[f'{sensor}_roll_std'] = train_df.groupby('unit_number')[sensor] \
        .transform(lambda x: x.rolling(window=window_size, min_periods=1).std())

# Fill NaNs (especially in std dev) with 0
train_df.fillna(0, inplace=True)

# Extended feature set
sensor_features_extended = sensor_cols + \
    [f'{sensor}_roll_mean' for sensor in sensor_cols] + \
    [f'{sensor}_roll_std' for sensor in sensor_cols]

print("Total features after adding rolling stats:", len(sensor_features_extended))

from imblearn.over_sampling import SMOTE

# Feature matrix and target (using extended features with rolling stats)
X = train_df[sensor_features_extended]
y = train_df['cluster']

# Split original train data for cross-validation evaluation
X_train, X_val, y_train, y_val = train_test_split(
    X, y, test_size=0.2, stratify=y, random_state=42
)

# Apply SMOTE on training set only
smote = SMOTE(random_state=42)
X_train_resampled, y_train_resampled = smote.fit_resample(X_train, y_train)

print("Before SMOTE:")
print(y_train.value_counts())
print("\nAfter SMOTE:")
print(pd.Series(y_train_resampled).value_counts())

"""## **Phase 3:-**"""

# Compute time to next degradation stage for each engine cycle
def compute_time_to_next_stage(df):
    df_sorted = df.sort_values(['unit_number', 'time_in_cycles'])
    time_to_next = []

    for unit_id in df_sorted['unit_number'].unique():
        unit_data = df_sorted[df_sorted['unit_number'] == unit_id]
        stages = unit_data['cluster'].values  # Use 'cluster' or 'degradation_stage' if renamed
        n = len(unit_data)

        for i in range(n):
            current_stage = stages[i]
            time = 0
            for j in range(i+1, n):
                time += 1
                if stages[j] != current_stage:
                    break
            else:
                time = 0  # No transition ahead
            time_to_next.append(time)

    df_sorted['time_to_next_stage'] = time_to_next
    return df_sorted

# Apply the function
df = compute_time_to_next_stage(train_df)  # Apply on labeled training set

from sklearn.ensemble import RandomForestRegressor

top_features = [
    'sensor_measurement_6', 'sensor_measurement_9', 'sensor_measurement_14',
    'sensor_measurement_11', 'sensor_measurement_7', 'sensor_measurement_12',
    'sensor_measurement_4', 'sensor_measurement_8', 'sensor_measurement_13',
    'sensor_measurement_15'
]

X_reg = df[top_features]
y_reg = df['time_to_next_stage']

# Train/test split
from sklearn.model_selection import train_test_split
X_reg_train, X_reg_test, y_reg_train, y_reg_test = train_test_split(
    X_reg, y_reg, test_size=0.2, random_state=42
)

# Use fewer trees for speed
regressor = RandomForestRegressor(n_estimators=50, random_state=42)
regressor.fit(X_reg_train, y_reg_train)

from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
import numpy as np

y_reg_pred = regressor.predict(X_reg_test)

rmse = np.sqrt(mean_squared_error(y_reg_test, y_reg_pred))
mae = mean_absolute_error(y_reg_test, y_reg_pred)
r2 = r2_score(y_reg_test, y_reg_pred)

print("Regression Metrics:")
print(f"Root Mean Squared Error (RMSE): {rmse:.2f}")
print(f"Mean Absolute Error (MAE): {mae:.2f}")
print(f"R² Score: {r2:.2f}")

import matplotlib.pyplot as plt

plt.figure(figsize=(8,6))
plt.scatter(y_reg_test, y_reg_pred, alpha=0.5)
plt.plot([0, max(y_reg_test)], [0, max(y_reg_test)], 'r--')  # Perfect prediction line
plt.xlabel('True Time to Next Stage')
plt.ylabel('Predicted Time to Next Stage')
plt.title('Regression: True vs Predicted Time-to-Next-Stage')
plt.grid(True)
plt.tight_layout()
plt.show()

"""## **Phase 4:-**"""

# Imports
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LinearRegression

# Dummy data
X = np.random.rand(100, 10)
y_classification = np.random.randint(0, 4, size=100)
y_regression = np.random.randint(10, 100, size=100)

# Train-test split
X_train, X_test, y_class_train, y_class_test, y_reg_train, y_reg_test = train_test_split(
    X, y_classification, y_regression, test_size=0.2, random_state=42)

# Train Classifier
classifier = RandomForestClassifier(random_state=42)
classifier.fit(X_train, y_class_train)

# Train Regressor
regressor = LinearRegression()
regressor.fit(X_train, y_reg_train)

# Simulate engine IDs
engine_ids = np.arange(len(X_test))

print("✅ Dummy Classifier, Regressor, and Engine IDs are ready!")

# Get failure probabilities
failure_probabilities = classifier.predict_proba(X_test)[:, 3]

# Get time left to failure
time_left_predictions = regressor.predict(X_test)

# Create DataFrame
risk_df = pd.DataFrame({
    'Failure_Probability': failure_probabilities,
    'Time_Left': time_left_predictions
})

risk_df.head()

# Raw Risk Score
risk_df['Raw_Risk_Score'] = risk_df['Failure_Probability'] * risk_df['Time_Left']

# Normalization (Min-Max)
min_score = risk_df['Raw_Risk_Score'].min()
max_score = risk_df['Raw_Risk_Score'].max()
risk_df['Normalized_Score'] = (risk_df['Raw_Risk_Score'] - min_score) / (max_score - min_score)

# Urgency-Based Inversion
risk_df['Urgency_Score'] = risk_df['Failure_Probability'] / (risk_df['Time_Left'] + 1e-6)

risk_df.head()

# Maintenance Alert
for idx, row in risk_df.iterrows():
    if row['Normalized_Score'] > 0.7:
        print(f"⚠️  Maintenance Alert for Engine {engine_ids[idx]}!")

"""## **FD001 & FD003 PHASE 1:-**"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import os

from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans
from sklearn.decomposition import PCA
from sklearn.manifold import TSNE

import tensorflow as tf
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Input, Dense

import kagglehub

path = kagglehub.dataset_download("behrad3d/nasa-cmaps")

print("Path to dataset files:", path)

import os

# This should show you the folder names inside the downloaded dataset
print(os.listdir(path))

# Define column names
column_names = ['unit_number', 'time_in_cycles'] + \
               [f'operational_setting_{i}' for i in range(1, 4)] + \
               [f'sensor_measurement_{i}' for i in range(1, 22)]

# Load FD001
df1 = pd.read_csv(f"{path}/CMaps/train_FD001.txt", sep=" ", header=None)
df1.dropna(axis=1, how='all', inplace=True)
df1.columns = column_names
df1['source'] = 'FD001'

# Load FD003
df3 = pd.read_csv(f"{path}/CMaps/train_FD003.txt", sep=" ", header=None)
df3.dropna(axis=1, how='all', inplace=True)
df3.columns = column_names
df3['source'] = 'FD003'

# Combine FD001 and FD003
df = pd.concat([df1, df3], ignore_index=True)
print("Shape of the combined dataset (FD001 + FD003):", df.shape)
df.head()

"""The first step is to cluster the data into 5 stages:
- normal(0)
- degraded(1)
- highly degraded(2)
- critical(3)
- failure(4)
"""

# Select only sensor measurements
sensor_cols = [col for col in df.columns if 'sensor' in col]
X = df[sensor_cols]

# Scale the data
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

import tensorflow as tf
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Input, Dense

input_dim = X_scaled.shape[1]
encoding_dim = 8

# Define Autoencoder
input_layer = Input(shape=(input_dim,))
encoded = Dense(16, activation='relu')(input_layer)
encoded = Dense(encoding_dim, activation='relu')(encoded)

decoded = Dense(16, activation='relu')(encoded)
decoded = Dense(input_dim, activation='linear')(decoded)

autoencoder = Model(inputs=input_layer, outputs=decoded)
encoder = Model(inputs=input_layer, outputs=encoded)

autoencoder.compile(optimizer='adam', loss='mse')
autoencoder.fit(X_scaled, X_scaled, epochs=50, batch_size=256, shuffle=True, verbose=1)

# Encode the input data
X_encoded = encoder.predict(X_scaled)

# KMeans clustering
from sklearn.cluster import KMeans

kmeans = KMeans(n_clusters=5, random_state=42)
df['cluster'] = kmeans.fit_predict(X_encoded)

# Sample for plotting
sample_df = df.sample(5000, random_state=42)

# Plot some key sensors
sensors_to_plot = ['sensor_measurement_2', 'sensor_measurement_3', 'sensor_measurement_4']

for sensor in sensors_to_plot:
    plt.figure(figsize=(12,6))
    sns.lineplot(x='time_in_cycles', y=sensor, hue='cluster', data=sample_df, palette='tab10')
    plt.title(f"{sensor} vs Time for Different Clusters")
    plt.xlabel('Time in Cycles')
    plt.ylabel(sensor)
    plt.legend(title='Cluster')
    plt.grid(True)
    plt.show()

# Add a 'stage' column based on the 'cluster' column
df['stage'] = df['cluster'].map({0: 'normal', 1: 'degraded', 2: 'highly degraded', 3: 'critical', 4: 'failure'})

from sklearn.manifold import TSNE
import matplotlib.pyplot as plt
import numpy as np # Make sure numpy is imported

# Run t-SNE on encoded features
tsne = TSNE(n_components=2, perplexity=30, n_iter=300, random_state=42)
X_tsne = tsne.fit_transform(X_encoded)

# Add t-SNE results to DataFrame
df['tsne-1'] = X_tsne[:, 0]
df['tsne-2'] = X_tsne[:, 1]

# Define unique stages and colors
stages = df['stage'].unique()
colors = plt.cm.viridis(np.linspace(0, 1, len(stages)))

# Plot manually using matplotlib
plt.figure(figsize=(10, 6))
for i, stage in enumerate(sorted(stages)):
    subset = df[df['stage'] == stage]
    plt.scatter(subset['tsne-1'], subset['tsne-2'], label=f'Stage {stage}', color=colors[i], alpha=0.7)

plt.title("t-SNE Visualization of Engine Health Stages")
plt.xlabel("t-SNE Component 1")
plt.ylabel("t-SNE Component 2")
plt.legend(title='Stage')
plt.grid(True)
plt.show()

"""## **Phase 2:-**"""

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import classification_report, confusion_matrix

# Define column names
column_names = ['unit_number', 'time_in_cycles'] + \
               [f'op_setting_{i}' for i in range(1, 4)] + \
               [f'sensor_measurement_{i}' for i in range(1, 22)]

# Load and label source
def load_file(path, fname, source):
    df = pd.read_csv(f"{path}/CMaps/{fname}", sep=" ", header=None)
    df.dropna(axis=1, how='all', inplace=True)
    df.columns = column_names
    df['source'] = source
    return df

# Replace 'path' with your actual dataset path
train_df = pd.concat([
    load_file(path, "train_FD001.txt", "FD001"),
    load_file(path, "train_FD003.txt", "FD003")
], ignore_index=True)

test_df = pd.concat([
    load_file(path, "test_FD001.txt", "FD001"),
    load_file(path, "test_FD003.txt", "FD003")
], ignore_index=True)

from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler

# Feature columns
sensor_cols = [col for col in train_df.columns if 'sensor_measurement' in col]

# Normalize sensor data
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(train_df[sensor_cols])

# Apply KMeans clustering (same as Phase 1)
kmeans = KMeans(n_clusters=5, random_state=42)
train_df['cluster'] = kmeans.fit_predict(X_train_scaled)

# Scale test data using training scaler
X_test_scaled = scaler.transform(test_df[sensor_cols])

# Labels (y_train from cluster labels)
X_train = train_df[sensor_cols]
y_train = train_df['cluster']

X_test = test_df[sensor_cols]  # Note: test labels are unknown in CMAPSS, so just predict

clf = RandomForestClassifier(n_estimators=100, random_state=42, class_weight='balanced')
clf.fit(X_train_scaled, y_train)

y_pred_test = clf.predict(X_test_scaled)

# Assign predictions to test dataframe
test_df['predicted_stage'] = y_pred_test

stage_map = {
    0: 'Stage 0: Normal',
    1: 'Stage 1: Slightly Degraded',
    2: 'Stage 2: Moderately Degraded',
    3: 'Stage 3: Critical',
    4: 'Stage 4: Failure'
}
test_df['predicted_stage_name'] = test_df['predicted_stage'].map(stage_map)

print("Stage distribution in test predictions:")
print(test_df['predicted_stage_name'].value_counts())

# Optional visualization
plt.figure(figsize=(10,6))
sns.countplot(data=test_df, x='predicted_stage_name', order=stage_map.values())
plt.title("Predicted Stages on Official Test Data")
plt.xlabel("Degradation Stage")
plt.ylabel("Count")
plt.grid(True)
plt.xticks(rotation=30)
plt.show()

# Reuse existing train_df with cluster labels
from sklearn.model_selection import train_test_split # Import train_test_split

X = train_df[sensor_cols]
y = train_df['cluster']

X_train_cv, X_val_cv, y_train_cv, y_val_cv = train_test_split(
    X, y, test_size=0.2, stratify=y, random_state=42
)

X_train_cv_scaled = scaler.fit_transform(X_train_cv)
X_val_cv_scaled = scaler.transform(X_val_cv)

clf_cv = RandomForestClassifier(n_estimators=100, random_state=42, class_weight='balanced')
clf_cv.fit(X_train_cv_scaled, y_train_cv)
y_pred_cv = clf_cv.predict(X_val_cv_scaled)

stage_names = ['Stage 0: Normal', 'Stage 1: Slightly Degraded', 'Stage 2: Moderately Degraded',
               'Stage 3: Critical', 'Stage 4: Failure']

print("Classification Report (Train Split Evaluation):\n")
print(classification_report(y_val_cv, y_pred_cv, target_names=stage_names))

cm = confusion_matrix(y_val_cv, y_pred_cv)
plt.figure(figsize=(8,6))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
            xticklabels=stage_names, yticklabels=stage_names)
plt.title("Confusion Matrix (Train-Only Cross-Validation)")
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.xticks(rotation=45)
plt.yticks(rotation=0)
plt.tight_layout()
plt.show()

# Use trained classifier from CV: clf_cv and sensor_cols
importances = clf_cv.feature_importances_
indices = np.argsort(importances)[::-1]

top_n = 10  # Number of top features to show
top_features = [sensor_cols[i] for i in indices[:top_n]]
top_scores = importances[indices[:top_n]]

plt.figure(figsize=(10, 6))
sns.barplot(x=top_scores, y=top_features)
plt.title("Top 10 Sensor Features by Importance (Random Forest)")
plt.xlabel("Importance Score")
plt.ylabel("Sensor Feature")
plt.grid(True)
plt.tight_layout()
plt.show()

import xgboost as xgb

# Use same stratified split as before
X = train_df[sensor_cols]
y = train_df['cluster']

X_train_xgb, X_val_xgb, y_train_xgb, y_val_xgb = train_test_split(
    X, y, test_size=0.2, stratify=y, random_state=42
)

# Scale inputs
scaler_xgb = StandardScaler()
X_train_xgb_scaled = scaler_xgb.fit_transform(X_train_xgb)
X_val_xgb_scaled = scaler_xgb.transform(X_val_xgb)

# Define and train model
xgb_model = xgb.XGBClassifier(
    objective='multi:softmax',
    num_class=5,
    eval_metric='mlogloss',
    use_label_encoder=False,
    n_estimators=100,
    max_depth=6,
    learning_rate=0.1,
    random_state=42
)

xgb_model.fit(X_train_xgb_scaled, y_train_xgb)

# Sort the training data by unit and cycle
train_df = train_df.sort_values(by=['unit_number', 'time_in_cycles'])

# Set window size for rolling calculations
window_size = 5

# Sensor columns
sensor_cols = [col for col in train_df.columns if 'sensor_measurement' in col]

# Create new rolling statistic columns
for sensor in sensor_cols:
    # Rolling mean
    train_df[f'{sensor}_roll_mean'] = train_df.groupby('unit_number')[sensor] \
        .transform(lambda x: x.rolling(window=window_size, min_periods=1).mean())

    # Rolling std dev
    train_df[f'{sensor}_roll_std'] = train_df.groupby('unit_number')[sensor] \
        .transform(lambda x: x.rolling(window=window_size, min_periods=1).std())

# Fill NaNs (especially in std dev) with 0
train_df.fillna(0, inplace=True)

# Extended feature set
sensor_features_extended = sensor_cols + \
    [f'{sensor}_roll_mean' for sensor in sensor_cols] + \
    [f'{sensor}_roll_std' for sensor in sensor_cols]

print("Total features after adding rolling stats:", len(sensor_features_extended))

from imblearn.over_sampling import SMOTE

# Feature matrix and target (using extended features with rolling stats)
X = train_df[sensor_features_extended]
y = train_df['cluster']

# Split original train data for cross-validation evaluation
X_train, X_val, y_train, y_val = train_test_split(
    X, y, test_size=0.2, stratify=y, random_state=42
)

# Apply SMOTE on training set only
smote = SMOTE(random_state=42)
X_train_resampled, y_train_resampled = smote.fit_resample(X_train, y_train)

print("Before SMOTE:")
print(y_train.value_counts())
print("\nAfter SMOTE:")
print(pd.Series(y_train_resampled).value_counts())

"""## **Phase 3:-**"""

# Compute time to next degradation stage for each engine cycle
def compute_time_to_next_stage(df):
    df_sorted = df.sort_values(['unit_number', 'time_in_cycles'])
    time_to_next = []

    for unit_id in df_sorted['unit_number'].unique():
        unit_data = df_sorted[df_sorted['unit_number'] == unit_id]
        stages = unit_data['cluster'].values  # Use 'cluster' or 'degradation_stage' if renamed
        n = len(unit_data)

        for i in range(n):
            current_stage = stages[i]
            time = 0
            for j in range(i+1, n):
                time += 1
                if stages[j] != current_stage:
                    break
            else:
                time = 0  # No transition ahead
            time_to_next.append(time)

    df_sorted['time_to_next_stage'] = time_to_next
    return df_sorted

# Apply the function
df = compute_time_to_next_stage(train_df)  # Apply on labeled training set

from sklearn.ensemble import RandomForestRegressor

top_features = [
    'sensor_measurement_7', 'sensor_measurement_6', 'sensor_measurement_11',
    'sensor_measurement_15', 'sensor_measurement_12', 'sensor_measurement_4',
    'sensor_measurement_8', 'sensor_measurement_10', 'sensor_measurement_20',
    'sensor_measurement_13'
]

X_reg = df[top_features]
y_reg = df['time_to_next_stage']

# Train/test split
from sklearn.model_selection import train_test_split
X_reg_train, X_reg_test, y_reg_train, y_reg_test = train_test_split(
    X_reg, y_reg, test_size=0.2, random_state=42
)

# Use fewer trees for speed
regressor = RandomForestRegressor(n_estimators=50, random_state=42)
regressor.fit(X_reg_train, y_reg_train)

from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
import numpy as np

y_reg_pred = regressor.predict(X_reg_test)

rmse = np.sqrt(mean_squared_error(y_reg_test, y_reg_pred))
mae = mean_absolute_error(y_reg_test, y_reg_pred)
r2 = r2_score(y_reg_test, y_reg_pred)

print("Regression Metrics:")
print(f"Root Mean Squared Error (RMSE): {rmse:.2f}")
print(f"Mean Absolute Error (MAE): {mae:.2f}")
print(f"R² Score: {r2:.2f}")

import matplotlib.pyplot as plt

plt.figure(figsize=(8,6))
plt.scatter(y_reg_test, y_reg_pred, alpha=0.5)
plt.plot([0, max(y_reg_test)], [0, max(y_reg_test)], 'r--')  # Perfect prediction line
plt.xlabel('True Time to Next Stage')
plt.ylabel('Predicted Time to Next Stage')
plt.title('Regression: True vs Predicted Time-to-Next-Stage')
plt.grid(True)
plt.tight_layout()
plt.show()

"""## **Phase 4:-**"""

# Imports
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LinearRegression

# Dummy data
X = np.random.rand(100, 10)
y_classification = np.random.randint(0, 4, size=100)
y_regression = np.random.randint(10, 100, size=100)

# Train-test split
X_train, X_test, y_class_train, y_class_test, y_reg_train, y_reg_test = train_test_split(
    X, y_classification, y_regression, test_size=0.2, random_state=42)

# Train Classifier
classifier = RandomForestClassifier(random_state=42)
classifier.fit(X_train, y_class_train)

# Train Regressor
regressor = LinearRegression()
regressor.fit(X_train, y_reg_train)

# Simulate engine IDs
engine_ids = np.arange(len(X_test))

print("✅ Dummy Classifier, Regressor, and Engine IDs are ready!")

# Get failure probabilities
failure_probabilities = classifier.predict_proba(X_test)[:, 3]

# Get time left to failure
time_left_predictions = regressor.predict(X_test)

# Create DataFrame
risk_df = pd.DataFrame({
    'Failure_Probability': failure_probabilities,
    'Time_Left': time_left_predictions
})

risk_df.head()

# Raw Risk Score
risk_df['Raw_Risk_Score'] = risk_df['Failure_Probability'] * risk_df['Time_Left']

# Normalization (Min-Max)
min_score = risk_df['Raw_Risk_Score'].min()
max_score = risk_df['Raw_Risk_Score'].max()
risk_df['Normalized_Score'] = (risk_df['Raw_Risk_Score'] - min_score) / (max_score - min_score)

# Urgency-Based Inversion
risk_df['Urgency_Score'] = risk_df['Failure_Probability'] / (risk_df['Time_Left'] + 1e-6)

risk_df.head()

# Maintenance Alert
for idx, row in risk_df.iterrows():
    if row['Normalized_Score'] > 0.7:
        print(f"⚠️  Maintenance Alert for Engine {engine_ids[idx]}!")

"""## **FD002 & FD004  Phase 1:-**"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import os

from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans
from sklearn.decomposition import PCA
from sklearn.manifold import TSNE

import tensorflow as tf
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Input, Dense

import kagglehub

path = kagglehub.dataset_download("behrad3d/nasa-cmaps")

print("Path to dataset files:", path)

import os

# This should show you the folder names inside the downloaded dataset
print(os.listdir(path))

# Define column names
column_names = ['unit_number', 'time_in_cycles'] + \
               [f'operational_setting_{i}' for i in range(1, 4)] + \
               [f'sensor_measurement_{i}' for i in range(1, 22)]

# Load FD002
df2 = pd.read_csv(f"{path}/CMaps/train_FD002.txt", sep=" ", header=None)
df2.dropna(axis=1, how='all', inplace=True)
df2.columns = column_names
df2['source'] = 'FD002'

# Load FD004
df4 = pd.read_csv(f"{path}/CMaps/train_FD004.txt", sep=" ", header=None)
df4.dropna(axis=1, how='all', inplace=True)
df4.columns = column_names
df4['source'] = 'FD004'

# Combine FD002 and FD004
df = pd.concat([df2, df4], ignore_index=True)
print("Shape of the combined dataset (FD002 + FD004):", df.shape)
df.head()

"""The first step is to cluster the data into 5 stages:
- normal(0)
- degraded(1)
- highly degraded(2)
- critical(3)
- failure(4)
"""

# Select only sensor measurements
sensor_cols = [col for col in df.columns if 'sensor' in col]
X = df[sensor_cols]

# Scale the data
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

import tensorflow as tf
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Input, Dense

input_dim = X_scaled.shape[1]
encoding_dim = 8

# Define Autoencoder
input_layer = Input(shape=(input_dim,))
encoded = Dense(16, activation='relu')(input_layer)
encoded = Dense(encoding_dim, activation='relu')(encoded)

decoded = Dense(16, activation='relu')(encoded)
decoded = Dense(input_dim, activation='linear')(decoded)

autoencoder = Model(inputs=input_layer, outputs=decoded)
encoder = Model(inputs=input_layer, outputs=encoded)

autoencoder.compile(optimizer='adam', loss='mse')
autoencoder.fit(X_scaled, X_scaled, epochs=50, batch_size=256, shuffle=True, verbose=1)

# Encode the input data
X_encoded = encoder.predict(X_scaled)

# KMeans clustering
from sklearn.cluster import KMeans

kmeans = KMeans(n_clusters=5, random_state=42)
df['cluster'] = kmeans.fit_predict(X_encoded)

# Sample for plotting
sample_df = df.sample(5000, random_state=42)

# Plot some key sensors
sensors_to_plot = ['sensor_measurement_2', 'sensor_measurement_3', 'sensor_measurement_4']

for sensor in sensors_to_plot:
    plt.figure(figsize=(12,6))
    sns.lineplot(x='time_in_cycles', y=sensor, hue='cluster', data=sample_df, palette='tab10')
    plt.title(f"{sensor} vs Time for Different Clusters")
    plt.xlabel('Time in Cycles')
    plt.ylabel(sensor)
    plt.legend(title='Cluster')
    plt.grid(True)
    plt.show()

# Add a 'stage' column based on the 'cluster' column
df['stage'] = df['cluster'].map({0: 'normal', 1: 'degraded', 2: 'highly degraded', 3: 'critical', 4: 'failure'})

from sklearn.manifold import TSNE
import matplotlib.pyplot as plt
import numpy as np # Make sure numpy is imported

# Run t-SNE on encoded features
tsne = TSNE(n_components=2, perplexity=30, n_iter=300, random_state=42)
X_tsne = tsne.fit_transform(X_encoded)

# Add t-SNE results to DataFrame
df['tsne-1'] = X_tsne[:, 0]
df['tsne-2'] = X_tsne[:, 1]

# Define unique stages and colors
stages = df['stage'].unique()
colors = plt.cm.viridis(np.linspace(0, 1, len(stages)))

# Plot manually using matplotlib
plt.figure(figsize=(10, 6))
for i, stage in enumerate(sorted(stages)):
    subset = df[df['stage'] == stage]
    plt.scatter(subset['tsne-1'], subset['tsne-2'], label=f'Stage {stage}', color=colors[i], alpha=0.7)

plt.title("t-SNE Visualization of Engine Health Stages")
plt.xlabel("t-SNE Component 1")
plt.ylabel("t-SNE Component 2")
plt.legend(title='Stage')
plt.grid(True)
plt.show()

"""## **Phase 2:-**"""

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import classification_report, confusion_matrix

# Define column names
column_names = ['unit_number', 'time_in_cycles'] + \
               [f'op_setting_{i}' for i in range(1, 4)] + \
               [f'sensor_measurement_{i}' for i in range(1, 22)]

# Load and label source
def load_file(path, fname, source):
    df = pd.read_csv(f"{path}/CMaps/{fname}", sep=" ", header=None)
    df.dropna(axis=1, how='all', inplace=True)
    df.columns = column_names
    df['source'] = source
    return df

# Replace 'path' with your actual dataset path
train_df = pd.concat([
    load_file(path, "train_FD002.txt", "FD002"),
    load_file(path, "train_FD004.txt", "FD004")
], ignore_index=True)

test_df = pd.concat([
    load_file(path, "test_FD002.txt", "FD002"),
    load_file(path, "test_FD004.txt", "FD004")
], ignore_index=True)

from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler

# Feature columns
sensor_cols = [col for col in train_df.columns if 'sensor_measurement' in col]

# Normalize sensor data
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(train_df[sensor_cols])

# Apply KMeans clustering (same as Phase 1)
kmeans = KMeans(n_clusters=5, random_state=42)
train_df['cluster'] = kmeans.fit_predict(X_train_scaled)

# Scale test data using training scaler
X_test_scaled = scaler.transform(test_df[sensor_cols])

# Labels (y_train from cluster labels)
X_train = train_df[sensor_cols]
y_train = train_df['cluster']

X_test = test_df[sensor_cols]  # Note: test labels are unknown in CMAPSS, so just predict

clf = RandomForestClassifier(n_estimators=100, random_state=42, class_weight='balanced')
clf.fit(X_train_scaled, y_train)

y_pred_test = clf.predict(X_test_scaled)

# Assign predictions to test dataframe
test_df['predicted_stage'] = y_pred_test

stage_map = {
    0: 'Stage 0: Normal',
    1: 'Stage 1: Slightly Degraded',
    2: 'Stage 2: Moderately Degraded',
    3: 'Stage 3: Critical',
    4: 'Stage 4: Failure'
}
test_df['predicted_stage_name'] = test_df['predicted_stage'].map(stage_map)

print("Stage distribution in test predictions:")
print(test_df['predicted_stage_name'].value_counts())

# Optional visualization
plt.figure(figsize=(10,6))
sns.countplot(data=test_df, x='predicted_stage_name', order=stage_map.values())
plt.title("Predicted Stages on Official Test Data")
plt.xlabel("Degradation Stage")
plt.ylabel("Count")
plt.grid(True)
plt.xticks(rotation=30)
plt.show()

# Reuse existing train_df with cluster labels
X = train_df[sensor_cols]
y = train_df['cluster']

X_train_cv, X_val_cv, y_train_cv, y_val_cv = train_test_split(
    X, y, test_size=0.2, stratify=y, random_state=42
)

X_train_cv_scaled = scaler.fit_transform(X_train_cv)
X_val_cv_scaled = scaler.transform(X_val_cv)

clf_cv = RandomForestClassifier(n_estimators=100, random_state=42, class_weight='balanced')
clf_cv.fit(X_train_cv_scaled, y_train_cv)
y_pred_cv = clf_cv.predict(X_val_cv_scaled)

stage_names = ['Stage 0: Normal', 'Stage 1: Slightly Degraded', 'Stage 2: Moderately Degraded',
               'Stage 3: Critical', 'Stage 4: Failure']

print("Classification Report (Train Split Evaluation):\n")
print(classification_report(y_val_cv, y_pred_cv, target_names=stage_names))

cm = confusion_matrix(y_val_cv, y_pred_cv)
plt.figure(figsize=(8,6))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
            xticklabels=stage_names, yticklabels=stage_names)
plt.title("Confusion Matrix (Train-Only Cross-Validation)")
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.xticks(rotation=45)
plt.yticks(rotation=0)
plt.tight_layout()
plt.show()

# Use trained classifier from CV: clf_cv and sensor_cols
importances = clf_cv.feature_importances_
indices = np.argsort(importances)[::-1]

top_n = 10  # Number of top features to show
top_features = [sensor_cols[i] for i in indices[:top_n]]
top_scores = importances[indices[:top_n]]

plt.figure(figsize=(10, 6))
sns.barplot(x=top_scores, y=top_features)
plt.title("Top 10 Sensor Features by Importance (Random Forest)")
plt.xlabel("Importance Score")
plt.ylabel("Sensor Feature")
plt.grid(True)
plt.tight_layout()
plt.show()

import xgboost as xgb

# Use same stratified split as before
X = train_df[sensor_cols]
y = train_df['cluster']

X_train_xgb, X_val_xgb, y_train_xgb, y_val_xgb = train_test_split(
    X, y, test_size=0.2, stratify=y, random_state=42
)

# Scale inputs
scaler_xgb = StandardScaler()
X_train_xgb_scaled = scaler_xgb.fit_transform(X_train_xgb)
X_val_xgb_scaled = scaler_xgb.transform(X_val_xgb)

# Define and train model
xgb_model = xgb.XGBClassifier(
    objective='multi:softmax',
    num_class=5,
    eval_metric='mlogloss',
    use_label_encoder=False,
    n_estimators=100,
    max_depth=6,
    learning_rate=0.1,
    random_state=42
)

xgb_model.fit(X_train_xgb_scaled, y_train_xgb)

# Sort the training data by unit and cycle
train_df = train_df.sort_values(by=['unit_number', 'time_in_cycles'])

# Set window size for rolling calculations
window_size = 5

# Sensor columns
sensor_cols = [col for col in train_df.columns if 'sensor_measurement' in col]

# Create new rolling statistic columns
for sensor in sensor_cols:
    # Rolling mean
    train_df[f'{sensor}_roll_mean'] = train_df.groupby('unit_number')[sensor] \
        .transform(lambda x: x.rolling(window=window_size, min_periods=1).mean())

    # Rolling std dev
    train_df[f'{sensor}_roll_std'] = train_df.groupby('unit_number')[sensor] \
        .transform(lambda x: x.rolling(window=window_size, min_periods=1).std())

# Fill NaNs (especially in std dev) with 0
train_df.fillna(0, inplace=True)

# Extended feature set
sensor_features_extended = sensor_cols + \
    [f'{sensor}_roll_mean' for sensor in sensor_cols] + \
    [f'{sensor}_roll_std' for sensor in sensor_cols]

print("Total features after adding rolling stats:", len(sensor_features_extended))

from imblearn.over_sampling import SMOTE

# Feature matrix and target (using extended features with rolling stats)
X = train_df[sensor_features_extended]
y = train_df['cluster']

# Split original train data for cross-validation evaluation
X_train, X_val, y_train, y_val = train_test_split(
    X, y, test_size=0.2, stratify=y, random_state=42
)

# Apply SMOTE on training set only
smote = SMOTE(random_state=42)
X_train_resampled, y_train_resampled = smote.fit_resample(X_train, y_train)

print("Before SMOTE:")
print(y_train.value_counts())
print("\nAfter SMOTE:")
print(pd.Series(y_train_resampled).value_counts())

"""## **Phase 3:-**"""

# Compute time to next degradation stage for each engine cycle
def compute_time_to_next_stage(df):
    df_sorted = df.sort_values(['unit_number', 'time_in_cycles'])
    time_to_next = []

    for unit_id in df_sorted['unit_number'].unique():
        unit_data = df_sorted[df_sorted['unit_number'] == unit_id]
        stages = unit_data['cluster'].values  # Use 'cluster' or 'degradation_stage' if renamed
        n = len(unit_data)

        for i in range(n):
            current_stage = stages[i]
            time = 0
            for j in range(i+1, n):
                time += 1
                if stages[j] != current_stage:
                    break
            else:
                time = 0  # No transition ahead
            time_to_next.append(time)

    df_sorted['time_to_next_stage'] = time_to_next
    return df_sorted

# Apply the function
df = compute_time_to_next_stage(train_df)  # Apply on labeled training set

from sklearn.ensemble import RandomForestRegressor

top_features = [
    'sensor_measurement_16', 'sensor_measurement_11', 'sensor_measurement_5',
    'sensor_measurement_4', 'sensor_measurement_2', 'sensor_measurement_3',
    'sensor_measurement_8', 'sensor_measurement_17', 'sensor_measurement_1',
    'sensor_measurement_12'
]

X_reg = df[top_features]
y_reg = df['time_to_next_stage']

# Train/test split
from sklearn.model_selection import train_test_split
X_reg_train, X_reg_test, y_reg_train, y_reg_test = train_test_split(
    X_reg, y_reg, test_size=0.2, random_state=42
)

# Use fewer trees for speed
regressor = RandomForestRegressor(n_estimators=50, random_state=42)
regressor.fit(X_reg_train, y_reg_train)

from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
import numpy as np

y_reg_pred = regressor.predict(X_reg_test)

rmse = np.sqrt(mean_squared_error(y_reg_test, y_reg_pred))
mae = mean_absolute_error(y_reg_test, y_reg_pred)
r2 = r2_score(y_reg_test, y_reg_pred)

print("Regression Metrics:")
print(f"Root Mean Squared Error (RMSE): {rmse:.2f}")
print(f"Mean Absolute Error (MAE): {mae:.2f}")
print(f"R² Score: {r2:.2f}")

import matplotlib.pyplot as plt

plt.figure(figsize=(8,6))
plt.scatter(y_reg_test, y_reg_pred, alpha=0.5)
plt.plot([0, max(y_reg_test)], [0, max(y_reg_test)], 'r--')  # Perfect prediction line
plt.xlabel('True Time to Next Stage')
plt.ylabel('Predicted Time to Next Stage')
plt.title('Regression: True vs Predicted Time-to-Next-Stage')
plt.grid(True)
plt.tight_layout()
plt.show()

"""## **Phase 4:-**"""

# Imports
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LinearRegression

# Dummy data
X = np.random.rand(100, 10)
y_classification = np.random.randint(0, 4, size=100)
y_regression = np.random.randint(10, 100, size=100)

# Train-test split
X_train, X_test, y_class_train, y_class_test, y_reg_train, y_reg_test = train_test_split(
    X, y_classification, y_regression, test_size=0.2, random_state=42)

# Train Classifier
classifier = RandomForestClassifier(random_state=42)
classifier.fit(X_train, y_class_train)

# Train Regressor
regressor = LinearRegression()
regressor.fit(X_train, y_reg_train)

# Simulate engine IDs
engine_ids = np.arange(len(X_test))

print("✅ Dummy Classifier, Regressor, and Engine IDs are ready!")

# Get failure probabilities
failure_probabilities = classifier.predict_proba(X_test)[:, 3]

# Get time left to failure
time_left_predictions = regressor.predict(X_test)

# Create DataFrame
risk_df = pd.DataFrame({
    'Failure_Probability': failure_probabilities,
    'Time_Left': time_left_predictions
})

risk_df.head()

# Raw Risk Score
risk_df['Raw_Risk_Score'] = risk_df['Failure_Probability'] * risk_df['Time_Left']

# Normalization (Min-Max)
min_score = risk_df['Raw_Risk_Score'].min()
max_score = risk_df['Raw_Risk_Score'].max()
risk_df['Normalized_Score'] = (risk_df['Raw_Risk_Score'] - min_score) / (max_score - min_score)

# Urgency-Based Inversion
risk_df['Urgency_Score'] = risk_df['Failure_Probability'] / (risk_df['Time_Left'] + 1e-6)

risk_df.head()

# Maintenance Alert
for idx, row in risk_df.iterrows():
    if row['Normalized_Score'] > 0.7:
        print(f"⚠️  Maintenance Alert for Engine {engine_ids[idx]}!")

"""## **ALL COMBINED PHASE 1:-**"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import os

from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans
from sklearn.decomposition import PCA
from sklearn.manifold import TSNE

import tensorflow as tf
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Input, Dense

import kagglehub

path = kagglehub.dataset_download("behrad3d/nasa-cmaps")

print("Path to dataset files:", path)

import os

# This should show you the folder names inside the downloaded dataset
print(os.listdir(path))

# Define column names
column_names = ['unit_number', 'time_in_cycles'] + \
               [f'operational_setting_{i}' for i in range(1, 4)] + \
               [f'sensor_measurement_{i}' for i in range(1, 22)]

# Load FD001
df1 = pd.read_csv(f"{path}/CMaps/train_FD001.txt", sep=" ", header=None)
df1.dropna(axis=1, how='all', inplace=True)
df1.columns = column_names
df1['source'] = 'FD001'

# Load FD002
df2 = pd.read_csv(f"{path}/CMaps/train_FD002.txt", sep=" ", header=None)
df2.dropna(axis=1, how='all', inplace=True)
df2.columns = column_names
df2['source'] = 'FD002'

# Load FD003
df3 = pd.read_csv(f"{path}/CMaps/train_FD003.txt", sep=" ", header=None)
df3.dropna(axis=1, how='all', inplace=True)
df3.columns = column_names
df3['source'] = 'FD003'

# Load FD004
df4 = pd.read_csv(f"{path}/CMaps/train_FD004.txt", sep=" ", header=None)
df4.dropna(axis=1, how='all', inplace=True)
df4.columns = column_names
df4['source'] = 'FD004'

# Combine all
df = pd.concat([df1, df2, df3, df4], ignore_index=True)
print("Shape of the combined dataset (FD001 + FD002 + FD003 + FD004):", df.shape)
df.head()

"""The first step is to cluster the data into 5 stages:
- normal(0)
- degraded(1)
- highly degraded(2)
- critical(3)
- failure(4)
"""

# Select only sensor measurements
sensor_cols = [col for col in df.columns if 'sensor' in col]
X = df[sensor_cols]

# Scale the data
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

import tensorflow as tf
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Input, Dense

input_dim = X_scaled.shape[1]
encoding_dim = 8

# Define Autoencoder
input_layer = Input(shape=(input_dim,))
encoded = Dense(16, activation='relu')(input_layer)
encoded = Dense(encoding_dim, activation='relu')(encoded)

decoded = Dense(16, activation='relu')(encoded)
decoded = Dense(input_dim, activation='linear')(decoded)

autoencoder = Model(inputs=input_layer, outputs=decoded)
encoder = Model(inputs=input_layer, outputs=encoded)

autoencoder.compile(optimizer='adam', loss='mse')
autoencoder.fit(X_scaled, X_scaled, epochs=50, batch_size=256, shuffle=True, verbose=1)

# Encode the input data
X_encoded = encoder.predict(X_scaled)

# KMeans clustering
from sklearn.cluster import KMeans

kmeans = KMeans(n_clusters=5, random_state=42)
df['cluster'] = kmeans.fit_predict(X_encoded)

# Sample for plotting
sample_df = df.sample(5000, random_state=42)

# Plot some key sensors
sensors_to_plot = ['sensor_measurement_2', 'sensor_measurement_3', 'sensor_measurement_4']

for sensor in sensors_to_plot:
    plt.figure(figsize=(12,6))
    sns.lineplot(x='time_in_cycles', y=sensor, hue='cluster', data=sample_df, palette='tab10')
    plt.title(f"{sensor} vs Time for Different Clusters")
    plt.xlabel('Time in Cycles')
    plt.ylabel(sensor)
    plt.legend(title='Cluster')
    plt.grid(True)
    plt.show()

# Add a 'stage' column based on the 'cluster' column
df['stage'] = df['cluster'].map({0: 'normal', 1: 'degraded', 2: 'highly degraded', 3: 'critical', 4: 'failure'})

from sklearn.manifold import TSNE
import matplotlib.pyplot as plt
import numpy as np # Make sure numpy is imported

# Run t-SNE on encoded features
tsne = TSNE(n_components=2, perplexity=30, n_iter=300, random_state=42)
X_tsne = tsne.fit_transform(X_encoded)

# Add t-SNE results to DataFrame
df['tsne-1'] = X_tsne[:, 0]
df['tsne-2'] = X_tsne[:, 1]

# Define unique stages and colors
stages = df['stage'].unique()
colors = plt.cm.viridis(np.linspace(0, 1, len(stages)))

# Plot manually using matplotlib
plt.figure(figsize=(10, 6))
for i, stage in enumerate(sorted(stages)):
    subset = df[df['stage'] == stage]
    plt.scatter(subset['tsne-1'], subset['tsne-2'], label=f'Stage {stage}', color=colors[i], alpha=0.7)

plt.title("t-SNE Visualization of Engine Health Stages")
plt.xlabel("t-SNE Component 1")
plt.ylabel("t-SNE Component 2")
plt.legend(title='Stage')
plt.grid(True)
plt.show()

"""## **Phase 2:-**"""

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import classification_report, confusion_matrix

# Define column names
column_names = ['unit_number', 'time_in_cycles'] + \
               [f'op_setting_{i}' for i in range(1, 4)] + \
               [f'sensor_measurement_{i}' for i in range(1, 22)]

# Load and label source
def load_file(path, fname, source):
    df = pd.read_csv(f"{path}/CMaps/{fname}", sep=" ", header=None)
    df.dropna(axis=1, how='all', inplace=True)
    df.columns = column_names
    df['source'] = source
    return df

# Replace 'path' with your actual dataset path
train_df = pd.concat([
    load_file(path, "train_FD001.txt", "FD001"),
    load_file(path, "train_FD002.txt", "FD002"),
    load_file(path, "train_FD003.txt", "FD003"),
    load_file(path, "train_FD004.txt", "FD004")
], ignore_index=True)

test_df = pd.concat([
    load_file(path, "test_FD001.txt", "FD001"),
    load_file(path, "test_FD002.txt", "FD002"),
    load_file(path, "test_FD003.txt", "FD003"),
    load_file(path, "test_FD004.txt", "FD004")
], ignore_index=True)

from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler

# Feature columns
sensor_cols = [col for col in train_df.columns if 'sensor_measurement' in col]

# Normalize sensor data
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(train_df[sensor_cols])

# Apply KMeans clustering (same as Phase 1)
kmeans = KMeans(n_clusters=5, random_state=42)
train_df['cluster'] = kmeans.fit_predict(X_train_scaled)

# Scale test data using training scaler
X_test_scaled = scaler.transform(test_df[sensor_cols])

# Labels (y_train from cluster labels)
X_train = train_df[sensor_cols]
y_train = train_df['cluster']

X_test = test_df[sensor_cols]  # Note: test labels are unknown in CMAPSS, so just predict

clf = RandomForestClassifier(n_estimators=100, random_state=42, class_weight='balanced')
clf.fit(X_train_scaled, y_train)

y_pred_test = clf.predict(X_test_scaled)

# Assign predictions to test dataframe
test_df['predicted_stage'] = y_pred_test

stage_map = {
    0: 'Stage 0: Normal',
    1: 'Stage 1: Slightly Degraded',
    2: 'Stage 2: Moderately Degraded',
    3: 'Stage 3: Critical',
    4: 'Stage 4: Failure'
}
test_df['predicted_stage_name'] = test_df['predicted_stage'].map(stage_map)

print("Stage distribution in test predictions:")
print(test_df['predicted_stage_name'].value_counts())

# Optional visualization
plt.figure(figsize=(10,6))
sns.countplot(data=test_df, x='predicted_stage_name', order=stage_map.values())
plt.title("Predicted Stages on Official Test Data")
plt.xlabel("Degradation Stage")
plt.ylabel("Count")
plt.grid(True)
plt.xticks(rotation=30)
plt.show()

# Reuse existing train_df with cluster labels
from sklearn.model_selection import train_test_split # Import train_test_split

X = train_df[sensor_cols]
y = train_df['cluster']

X_train_cv, X_val_cv, y_train_cv, y_val_cv = train_test_split(
    X, y, test_size=0.2, stratify=y, random_state=42
)

X_train_cv_scaled = scaler.fit_transform(X_train_cv)
X_val_cv_scaled = scaler.transform(X_val_cv)

clf_cv = RandomForestClassifier(n_estimators=100, random_state=42, class_weight='balanced')
clf_cv.fit(X_train_cv_scaled, y_train_cv)
y_pred_cv = clf_cv.predict(X_val_cv_scaled)

stage_names = ['Stage 0: Normal', 'Stage 1: Slightly Degraded', 'Stage 2: Moderately Degraded',
               'Stage 3: Critical', 'Stage 4: Failure']

print("Classification Report (Train Split Evaluation):\n")
print(classification_report(y_val_cv, y_pred_cv, target_names=stage_names))

cm = confusion_matrix(y_val_cv, y_pred_cv)
plt.figure(figsize=(8,6))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
            xticklabels=stage_names, yticklabels=stage_names)
plt.title("Confusion Matrix (Train-Only Cross-Validation)")
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.xticks(rotation=45)
plt.yticks(rotation=0)
plt.tight_layout()
plt.show()

# Use trained classifier from CV: clf_cv and sensor_cols
importances = clf_cv.feature_importances_
indices = np.argsort(importances)[::-1]

top_n = 10  # Number of top features to show
top_features = [sensor_cols[i] for i in indices[:top_n]]
top_scores = importances[indices[:top_n]]

plt.figure(figsize=(10, 6))
sns.barplot(x=top_scores, y=top_features)
plt.title("Top 10 Sensor Features by Importance (Random Forest)")
plt.xlabel("Importance Score")
plt.ylabel("Sensor Feature")
plt.grid(True)
plt.tight_layout()
plt.show()

import xgboost as xgb

# Use same stratified split as before
X = train_df[sensor_cols]
y = train_df['cluster']

X_train_xgb, X_val_xgb, y_train_xgb, y_val_xgb = train_test_split(
    X, y, test_size=0.2, stratify=y, random_state=42
)

# Scale inputs
scaler_xgb = StandardScaler()
X_train_xgb_scaled = scaler_xgb.fit_transform(X_train_xgb)
X_val_xgb_scaled = scaler_xgb.transform(X_val_xgb)

# Define and train model
xgb_model = xgb.XGBClassifier(
    objective='multi:softmax',
    num_class=5,
    eval_metric='mlogloss',
    use_label_encoder=False,
    n_estimators=100,
    max_depth=6,
    learning_rate=0.1,
    random_state=42
)

xgb_model.fit(X_train_xgb_scaled, y_train_xgb)

# Sort the training data by unit and cycle
train_df = train_df.sort_values(by=['unit_number', 'time_in_cycles'])

# Set window size for rolling calculations
window_size = 5

# Sensor columns
sensor_cols = [col for col in train_df.columns if 'sensor_measurement' in col]

# Create new rolling statistic columns
for sensor in sensor_cols:
    # Rolling mean
    train_df[f'{sensor}_roll_mean'] = train_df.groupby('unit_number')[sensor] \
        .transform(lambda x: x.rolling(window=window_size, min_periods=1).mean())

    # Rolling std dev
    train_df[f'{sensor}_roll_std'] = train_df.groupby('unit_number')[sensor] \
        .transform(lambda x: x.rolling(window=window_size, min_periods=1).std())

# Fill NaNs (especially in std dev) with 0
train_df.fillna(0, inplace=True)

# Extended feature set
sensor_features_extended = sensor_cols + \
    [f'{sensor}_roll_mean' for sensor in sensor_cols] + \
    [f'{sensor}_roll_std' for sensor in sensor_cols]

print("Total features after adding rolling stats:", len(sensor_features_extended))

from imblearn.over_sampling import SMOTE

# Feature matrix and target (using extended features with rolling stats)
X = train_df[sensor_features_extended]
y = train_df['cluster']

# Split original train data for cross-validation evaluation
X_train, X_val, y_train, y_val = train_test_split(
    X, y, test_size=0.2, stratify=y, random_state=42
)

# Apply SMOTE on training set only
smote = SMOTE(random_state=42)
X_train_resampled, y_train_resampled = smote.fit_resample(X_train, y_train)

print("Before SMOTE:")
print(y_train.value_counts())
print("\nAfter SMOTE:")
print(pd.Series(y_train_resampled).value_counts())

"""## **Phase 3:-**"""

# Compute time to next degradation stage for each engine cycle
def compute_time_to_next_stage(df):
    df_sorted = df.sort_values(['unit_number', 'time_in_cycles'])
    time_to_next = []

    for unit_id in df_sorted['unit_number'].unique():
        unit_data = df_sorted[df_sorted['unit_number'] == unit_id]
        stages = unit_data['cluster'].values  # Use 'cluster' or 'degradation_stage' if renamed
        n = len(unit_data)

        for i in range(n):
            current_stage = stages[i]
            time = 0
            for j in range(i+1, n):
                time += 1
                if stages[j] != current_stage:
                    break
            else:
                time = 0  # No transition ahead
            time_to_next.append(time)

    df_sorted['time_to_next_stage'] = time_to_next
    return df_sorted

# Apply the function
df = compute_time_to_next_stage(train_df)  # Apply on labeled training set

from sklearn.ensemble import RandomForestRegressor

top_features = [
    'sensor_measurement_16', 'sensor_measurement_11', 'sensor_measurement_4',
    'sensor_measurement_9', 'sensor_measurement_8', 'sensor_measurement_5',
    'sensor_measurement_2', 'sensor_measurement_1', 'sensor_measurement_7',
    'sensor_measurement_6'
]

X_reg = df[top_features]
y_reg = df['time_to_next_stage']

# Train/test split
from sklearn.model_selection import train_test_split
X_reg_train, X_reg_test, y_reg_train, y_reg_test = train_test_split(
    X_reg, y_reg, test_size=0.2, random_state=42
)

# Use fewer trees for speed
regressor = RandomForestRegressor(n_estimators=50, random_state=42)
regressor.fit(X_reg_train, y_reg_train)

from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
import numpy as np

y_reg_pred = regressor.predict(X_reg_test)

rmse = np.sqrt(mean_squared_error(y_reg_test, y_reg_pred))
mae = mean_absolute_error(y_reg_test, y_reg_pred)
r2 = r2_score(y_reg_test, y_reg_pred)

print("Regression Metrics:")
print(f"Root Mean Squared Error (RMSE): {rmse:.2f}")
print(f"Mean Absolute Error (MAE): {mae:.2f}")
print(f"R² Score: {r2:.2f}")

import matplotlib.pyplot as plt

plt.figure(figsize=(8,6))
plt.scatter(y_reg_test, y_reg_pred, alpha=0.5)
plt.plot([0, max(y_reg_test)], [0, max(y_reg_test)], 'r--')  # Perfect prediction line
plt.xlabel('True Time to Next Stage')
plt.ylabel('Predicted Time to Next Stage')
plt.title('Regression: True vs Predicted Time-to-Next-Stage')
plt.grid(True)
plt.tight_layout()
plt.show()

"""## **Phase 4:-**"""

# Imports
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LinearRegression

# Dummy data
X = np.random.rand(100, 10)
y_classification = np.random.randint(0, 4, size=100)
y_regression = np.random.randint(10, 100, size=100)

# Train-test split
X_train, X_test, y_class_train, y_class_test, y_reg_train, y_reg_test = train_test_split(
    X, y_classification, y_regression, test_size=0.2, random_state=42)

# Train Classifier
classifier = RandomForestClassifier(random_state=42)
classifier.fit(X_train, y_class_train)

# Train Regressor
regressor = LinearRegression()
regressor.fit(X_train, y_reg_train)

# Simulate engine IDs
engine_ids = np.arange(len(X_test))

print("✅ Dummy Classifier, Regressor, and Engine IDs are ready!")

# Get failure probabilities
failure_probabilities = classifier.predict_proba(X_test)[:, 3]

# Get time left to failure
time_left_predictions = regressor.predict(X_test)

# Create DataFrame
risk_df = pd.DataFrame({
    'Failure_Probability': failure_probabilities,
    'Time_Left': time_left_predictions
})

risk_df.head()

# Raw Risk Score
risk_df['Raw_Risk_Score'] = risk_df['Failure_Probability'] * risk_df['Time_Left']

# Normalization (Min-Max)
min_score = risk_df['Raw_Risk_Score'].min()
max_score = risk_df['Raw_Risk_Score'].max()
risk_df['Normalized_Score'] = (risk_df['Raw_Risk_Score'] - min_score) / (max_score - min_score)

# Urgency-Based Inversion
risk_df['Urgency_Score'] = risk_df['Failure_Probability'] / (risk_df['Time_Left'] + 1e-6)

risk_df.head()

# Maintenance Alert
for idx, row in risk_df.iterrows():
    if row['Normalized_Score'] > 0.7:
        print(f"⚠️  Maintenance Alert for Engine {engine_ids[idx]}!")

import matplotlib.pyplot as plt

# Simulate time progression for a few engines
risk_df['Cycle'] = np.tile(np.arange(1, len(risk_df)+1), 1)  # Simple cycle mock

plt.figure(figsize=(10,5))
plt.plot(risk_df['Cycle'], risk_df['Normalized_Score'], label='Normalized Risk Score')
plt.axhline(0.7, color='red', linestyle='--', label='Alert Threshold')
plt.xlabel("Cycle")
plt.ylabel("Normalized Risk Score")
plt.title("Simulated Risk Score Over Time")
plt.legend()
plt.grid(True)
plt.tight_layout()
plt.show()